### PR TITLE
Support ssl

### PR DESCRIPTION
**Pull request by nilroy**
This PR adds ssl support for collecting etcd metrics

### CODE REVIEW

**Comment by nilroy** [comment]
@mattyjones for your review

**Comment by nilroy** [comment]
@mattyjones any update on this? Can I get this PR merged and a new gem out of it?

**Comment by sstarcher** [comment]
sorry for the wait

**Comment by nilroy** [comment]
@sstarcher What is the version of the gem that contains my changes?

**Comment by sstarcher** [comment]
@nilroy a new release has not been cut

**Comment by nilroy** [comment]
@sstarcher roger that.. Will wait for the new release :)

**Pull request merged**
